services:
  - type: web
    name: google-sheet-student-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: LOCAL_DEMO_ENABLED
        value: "false"
      - key: MOCK_SHEET_ENABLED
        value: "false"
